#!/usr/bin/env bash
set -Eeuo pipefail

managed="$(mktemp "${TMPDIR:-/tmp}/dotfiles-managed-apps.XXXXXX")"
installed="$(mktemp "${TMPDIR:-/tmp}/dotfiles-installed-apps.XXXXXX")"
trap 'rm -f "$managed" "$installed"' EXIT

if command -v brew >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
  casks="$(brew list --cask 2>/dev/null || true)"
  if [[ -n "$casks" ]]; then
    # Cask tokens cannot be compared to app bundle names; use their declared artifacts.
    brew info --json=v2 --cask $casks 2>/dev/null |
      jq -r '.casks[].artifacts[]? | .app? // empty | if type == "array" then .[] else . end' |
      while IFS= read -r app; do basename "$app"; done >>"$managed"
  fi
fi

for directory in /Applications "$HOME/Applications"; do
  [[ -d "$directory" ]] || continue
  while IFS= read -r -d '' app; do
    name="${app##*/}"
    [[ "$name" == .* ]] && continue
    printf '%s\n' "$name" >>"$installed"

    store_id="$(mdls -raw -name kMDItemAppStoreAdamID "$app" 2>/dev/null || true)"
    [[ "$store_id" =~ ^[0-9]+$ ]] && printf '%s\n' "$name" >>"$managed"
  done < <(find "$directory" -maxdepth 1 -type d -name '*.app' -print0)
done

LC_ALL=C sort -u "$managed" -o "$managed"
LC_ALL=C sort -u "$installed" -o "$installed"

cat <<'EOF'
# Discovered unmanaged apps

Generated by `~/.dotfiles/bin/dotfiles apps-snapshot`. These app bundles are
installed but are not currently represented by Homebrew Cask or the Mac App Store.
Review them with `packages/manual.md`; do not add secrets or installer files here.

EOF

comm -23 "$installed" "$managed" | sed 's/^/- /'
